### ISSUE TITLE
Inclusion in proptest?

### ISSUE THREAD

**Issue by Andlon** [frozenlib/test-strategy#1]
Hi, I just came across this library, and, at least judging from the README, it looks amazing. Have you considered proposing to include this functionality in `proptest` proper? Assuming the maintainers of `proptest` would want this, it would make these macros more accessible to users, and it would prevent possible version incompatibilities.

**Comment by frozenlib** [comment]
I have thought about suggesting integration but stopped it because it seemed more interesting to add features without worrying about compatibility.

However, I would be happy if this feature could be used in `proptest` directly.

**Comment by sorairolake** [comment]
It seems that a procedural macro similar to `#[proptest]` was added in proptest-rs/proptest#316.

**Comment by Andlon** [comment]
Thanks for the heads-up @sorairolake! I'll close this issue.
