### ISSUE TITLE
Mutable function arguments when using the 'strategy' attribute.

### ISSUE THREAD

**Issue by Lemmih** [frozenlib/test-strategy#2]
Hi,

This code doesn't work because `#[strategy(..)]` apparently strips the `mut` keyword.

```rust
#[proptest]
fn test(#[strategy(1..2)] mut x: i32) {
  x = 0;
}
```

It would be nice to keep the `mut` keyword. My usecase is for generating a `Vec` and then removing duplicates.

**Comment by frozenlib** [comment]
Thanks for posting the issue.

I have fixed this issue in 55646548e7ca5557db54b0aa24913044682eeb82.

**Comment by Lemmih** [comment]
Awesome!

**Comment by brunocodutra** [comment]
@frozenlib anything missing before a new version that includes this fix can be released? Anything you need help with?

**Comment by frozenlib** [comment]
There didn't seem to be any problems, so I have just released a new version.
