### ISSUE TITLE
Use `Index` for dependent ranges?

### ISSUE THREAD

**Issue by sunshowers** [frozenlib/test-strategy#7]
Hi there --

Thanks for writing test-strategy! As a long-time proptest user I've been using it for a bit and really love it.

One thing I noticed is that currently, dependent strategies [compile down to `prop_flat_map`](https://github.com/frozenlib/test-strategy/blob/561271062abb723d56fa7527ed3af3ef657f325c/src/arbitrary.rs#L604). As you likely know, `prop_flat_map` (monadic bind) is a bit weird because it makes shrinking quite chaotic.

Proptest does provide an important special case for dependent distributions that are generated uniformly at random: [`sample::Index`](https://docs.rs/proptest/latest/proptest/sample/struct.Index.html). (In my experience this solves most of the use cases which folks use flat_map for). I'm wondering if it would make sense to optimize some cases into indexes.

For example, for the input:

```rust
#[derive(Debug, Arbitrary)]
#[arbitrary(dump)]
struct Args {
    main: u64,
    #[strategy(0..=#main))]
    dependent: u64,
}
```

[The code that's generated](https://gist.github.com/sunshowers/6137366d12c15c8f2a03b78c1c588ab5) uses a `prop_flat_map`. Instead, however, the implementation could be an automated version of:

```rust
impl Arbitrary for Args {
    type Parameters = ();
    type Strategy = BoxedStrategy<Self>;
    fn arbitrary_with(
        args: <Self as proptest::arbitrary::Arbitrary>::Parameters,
    ) -> Self::Strategy {
        (any::<u64>(), any::<proptest::sample::Index>())
            .prop_map(|main, dependent_index| {
                let dependent = dependent_index.index(main + 1);
                Self { main, dependent }
            })
            .boxed()
    }
}
```

I'm not sure how error-prone it might be to analyze existing expressions, so maybe we could potentially introduce a special annotation for it, e.g. `#[strategy(@dependent_range(0, #main + 1))]`.

Would love to hear your thoughts!

**Comment by frozenlib** [comment]
Thanks for the suggestion.

If I wanted to use `sample::Index`, I would intuitively write something like the following, but the current implementation doesn't correctly determine the dependency.

```rust
#[derive(Debug, Arbitrary)]
struct Args {
    main: usize,
    #[strategy(any::<proptest::sample::Index>().prop_map(move |i| i.index(#main)))]
    dependent: usize,
}
```

In the case of `prop_filter`, using `#[filter]` instead of `prop_filter` allows the macro to correctly understand the dependencies.

In the same way, I think it would be easier to use `sample::Index` by allowing `#[map]` to be used instead of `prop_map` as shown below, so that the macro can understand the dependencies.

```rust
#[derive(Debug, Arbitrary)]
struct Args {
    main: usize,
    #[strategy(any::<proptest::sample::Index>())]
    #[map(move |i: proptest::sample::Index| i.index(#main))]
    dependent: usize,
}

#[derive(Debug, Arbitrary)]
struct Args {
    main: usize,
    #[map(move |i: proptest::sample::Index| i.index(#main))]
    dependent: usize,
}

#[derive(Debug, Arbitrary)]
struct Args {
    main: usize,
    #[map(dependent_range(0, #main + 1))]
    dependent: usize,
}

fn dependent_range(start: usize, end: usize) -> impl Fn(proptest::sample::Index) -> usize {
    move |i| start + i.index(end - start)
}
```

**Comment by frozenlib** [comment]
I made `#[map(...)]` available. (ba368b672bb66c19348c2d99772878b111336296)

**Comment by sunshowers** [comment]
Thank you, I love that approach!
